import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "./components/Navigation";

const allianceNo2 = localFont({
  src: [
    {
      path: "../public/fonts/alliance-no-2/AllianceNo2-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/alliance-no-2/AllianceNo2-Medium.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-primary",
  display: "swap",
  fallback: ["-apple-system", "BlinkMacSystemFont", "sans-serif"],
});

const switzer = localFont({
  src: [
    {
      path: "../public/fonts/switzer/Switzer-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/switzer/Switzer-Medium.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-secondary",
  display: "swap",
  fallback: ["-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${allianceNo2.variable} ${switzer.variable} antialiased`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
